model_name: "GraphSAGE_mean"
aggregator: "mean"
num_layers: 2
hidden_size: 16
agg_transform_size: 16  # only needed for maxpool and meanpool aggregator
dropout_prob: 0.5

learning_rate: 0.01
weight_decay: !!float 5e-4